import fs from 'node:fs'
import path from 'node:path'
import { PKG, resolveFrom } from '../core/paths'
import type { DesignProject } from '../core/project'
import type { ScreenSource } from '../core/sources'
import { toPosix } from '../core/text'

export const SYSTEM_CSS = 'system.css'
export const HTML_BOOT = 'html-boot.js'

function writeIfChanged(file: string, content: string): boolean {
  try {
    if (fs.readFileSync(file, 'utf8') === content) return false
  } catch {}
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, content)
  return true
}

function importPath(fromDir: string, file: string): string {
  const rel = toPosix(path.relative(fromDir, file))
  return rel.startsWith('.') ? rel : `./${rel}`
}

const css = (file: string) => JSON.stringify(toPosix(file))

/** The generated modules each frame loads, kept in `.design/.cache/entries`. */
export class Entries {
  constructor(private readonly project: DesignProject) {}

  get dir(): string {
    return this.project.paths.entries
  }

  systemCssFile(): string {
    return path.join(this.dir, SYSTEM_CSS)
  }

  entryFile(source: ScreenSource): string {
    return path.join(this.dir, source.canvas, `${source.id}.js`)
  }

  /** Tailwind with the design tokens, or the stylesheet system.json names; scans every file in `.design`. */
  systemCss(): string {
    const { paths } = this.project
    const system = this.project.system()
    const { config } = this.project.config()
    const lines: string[] = ['/* Generated by foss-design. Edit .design/system/tokens.css instead. */']
    if (system?.stylesheet) {
      lines.push(`@import ${css(system.stylesheet)};`)
    } else {
      const tailwind = resolveFrom(PKG.manifest, 'tailwindcss/index.css')
      if (!tailwind) throw new Error('tailwindcss is missing from foss-design; reinstall the package')
      lines.push(`@import ${css(tailwind)} source(none);`, `@import ${css(PKG.baseCss)};`)
      if (system?.tokensFile) lines.push(`@import ${css(system.tokensFile)};`)
    }
    lines.push(`@source ${css(paths.design)};`, `@source not ${css(paths.cache)};`)
    lines.push(`@source not ${css(path.join(paths.design, 'node_modules'))};`)
    for (const extra of config.sources ?? []) lines.push(`@source ${css(path.resolve(paths.root, extra))};`)
    return `${lines.join('\n')}\n`
  }

  entrySource(source: ScreenSource): string {
    const file = this.entryFile(source)
    const dir = path.dirname(file)
    const lines: string[] = []
    if (source.system) lines.push(`import ${JSON.stringify(importPath(dir, this.systemCssFile()))}`)
    if (source.builtin === 'typography') {
      lines.push(
        `import { hmr, mount, TypographySpecimen } from '@design/runtime'`,
        'hmr(import.meta.hot)',
        'mount(TypographySpecimen)',
      )
    } else {
      lines.push(
        `import { hmr, mount } from '@design/runtime'`,
        `import * as screen from ${JSON.stringify(importPath(dir, source.file))}`,
        '',
        `const Screen = screen.default ?? Object.values(screen).find((value) => typeof value === 'function')`,
        'if (!Screen) throw new Error(' +
          JSON.stringify(`${path.basename(source.file)} has no component to render: export one as default`) +
          ')',
        'hmr(import.meta.hot)',
        'mount(Screen)',
      )
    }
    return `// Generated by foss-design for ${source.key}.\n${lines.join('\n')}\n`
  }

  /** Write every entry the project needs and drop the ones it no longer does. */
  sync(): void {
    writeIfChanged(this.systemCssFile(), this.systemCss())
    writeIfChanged(
      path.join(this.dir, HTML_BOOT),
      `// Generated by foss-design.\nimport { boot, hmr } from '@design/runtime'\nboot()\nhmr(import.meta.hot)\n`,
    )
    const wanted = new Set<string>([this.systemCssFile(), path.join(this.dir, HTML_BOOT)])
    for (const source of this.project.sources()) {
      if (source.format !== 'module') continue
      const file = this.entryFile(source)
      wanted.add(file)
      writeIfChanged(file, this.entrySource(source))
    }
    this.prune(this.dir, wanted)
  }

  /**
   * What the dev server scans for dependencies before any frame loads: the generated entries,
   * the HTML screens and the boot they load. A dependency found only once frames load makes
   * Vite bundle again and fail the requests in flight (504 Outdated Optimize Dep).
   */
  files(): string[] {
    const files = [path.join(this.dir, HTML_BOOT)]
    for (const source of this.project.sources()) {
      if (source.format === 'module') files.push(this.entryFile(source))
      else if (!source.builtin && fs.existsSync(source.file)) files.push(source.file)
    }
    return files
  }

  private prune(dir: string, wanted: Set<string>) {
    if (!fs.existsSync(dir)) return
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        this.prune(full, wanted)
        if (fs.readdirSync(full).length === 0) fs.rmdirSync(full)
      } else if (!wanted.has(full)) fs.rmSync(full)
    }
  }
}
